apiVersion: v1 
kind: Service 
metadata: 
  name: backend #note: my frontend application expects this to be exactly "backend"
  labels:
    name: backend-service 
    app: airbnz
spec: 
  type: ClusterIP #groups the backend pods together
  ports: 
  - port: 3001
    targetPort: 3001
  selector: #copy the labels from the backend-pod.yaml file into the selector below
    app: airbnz 
    tier: backend 
    
    
