apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: airbnz 
    tier: frontend 
spec: 
  containers:
  - name: frontend-container 
    image: nzoam93/airbnz-frontend
    ports:
    - containerPort: 80 #because nginx frontend listening on port 80
